spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/GiacomoGranzotto/SpringConfig
          repos:
            ryr:
                pattern: *-ryr
                cloneOnStart: false
                uri: https://github.com/GiacomoGranzotto/SpringConfig
            dlh:
                pattern: *-dlh
                cloneOnStart: false
                uri: https://github.com/GiacomoGranzotto/SpringConfig
